<?php
/**
 * Starter content for every treatment page listed in the rebuild brief.
 * URLs match the existing site exactly. Copy is written conservatively (no
 * guaranteed outcomes) and every record is flagged "needs review" in the
 * dashboard so the team can paste/approve the original clinical copy.
 */
return [
    // ---------------- Medical Treatments ----------------
    [
        'slug' => 'trigger-point-and-joint-injections', 'title' => 'Trigger Point & Joint Injections', 'category' => 'medical', 'icon' => 'syringe',
        'excerpt' => "Targeted in-office injections that may help calm painful muscle knots and irritated joints so you can move and participate in rehab more comfortably.",
        'hero_text' => "Precise, in-office injections for stubborn muscle knots and painful joints — delivered by our medical providers as part of an integrated care plan.",
        'what_is' => "Trigger points are tight, irritable bands within a muscle that can refer pain to other areas — a knot in the upper back, for example, may contribute to neck pain or headaches. Joints such as the knee, shoulder or hip can also become inflamed and painful.\n\nTrigger point and joint injections deliver medication directly to the source of pain. Depending on your evaluation, an injection may include a local anesthetic and/or another medication selected by your provider.",
        'conditions' => "Muscle knots and spasms\nNeck and upper back pain\nLow back pain\nShoulder pain\nKnee and hip joint pain\nTension-type headaches",
        'how_it_works' => "After reviewing your history and examining the area, your provider identifies the trigger point or joint to be treated. The skin is cleaned, and a fine needle is used to place the medication precisely. Many joint injections can be guided by ultrasound for added accuracy.",
        'benefits' => "May help relieve localized muscle and joint pain\nMay reduce muscle tension and spasm\nDesigned to support participation in rehab and stretching\nQuick in-office procedure with minimal downtime",
        'what_to_expect' => "Most injections take only a few minutes. You may feel brief pressure or a pinch. Some patients notice soreness at the injection site for a day or two. Your provider will explain aftercare and how the injection fits with the rest of your care plan. Eligibility is determined after evaluation.",
        'faqs' => [["Do the injections hurt?", "Most patients describe a brief pinch and pressure. Your provider will discuss comfort options before the procedure."], ["How many injections will I need?", "It depends on your condition and response. Your provider will recommend a plan after your evaluation."]],
        'related' => 'ultrasound-guided-injections-and-diagnostics,regenerative-medicine,pens-dry-needling-treatment,myofascial-release',
        'body_areas' => 'neck,shoulder,back,hip,knee,joint', 'featured' => 1,
    ],
    [
        'slug' => 'ultrasound-guided-injections-and-diagnostics', 'title' => 'Ultrasound Guided Injections & Diagnostics', 'category' => 'medical', 'icon' => 'scan',
        'excerpt' => "Real-time ultrasound imaging helps our providers see soft tissues and joints, evaluate the problem area and guide injections with precision.",
        'hero_text' => "See what's happening beneath the surface. Diagnostic ultrasound and image-guided injections help our providers target care precisely.",
        'what_is' => "Musculoskeletal ultrasound uses sound waves to create real-time images of muscles, tendons, ligaments and joints. It allows your provider to look at the painful area while you move, without radiation.\n\nWhen an injection is recommended, ultrasound guidance lets the provider watch the needle in real time and place the medication exactly where it is intended.",
        'conditions' => "Tendon and ligament irritation\nJoint swelling and effusion\nShoulder, elbow and wrist pain\nKnee and hip pain\nBursitis\nSoft tissue injuries",
        'how_it_works' => "A small amount of gel is applied to the skin and a handheld transducer is moved over the area. Images appear on a screen immediately. For guided injections, the provider uses the live image to direct the needle to the target structure.",
        'benefits' => "Real-time view of soft tissues and joints\nDesigned to improve injection accuracy\nNo radiation exposure\nHelps inform a personalized treatment plan",
        'what_to_expect' => "A diagnostic scan is painless and usually completed during your visit. If an injection is performed, you may have mild soreness afterward. Your provider will review findings with you and explain next steps.",
        'faqs' => [["Is ultrasound safe?", "Diagnostic ultrasound uses sound waves rather than radiation and is widely used in musculoskeletal care."], ["Why guide an injection with ultrasound?", "Guidance allows the provider to see the target structure and needle in real time, which is designed to improve placement accuracy."]],
        'related' => 'trigger-point-and-joint-injections,regenerative-medicine,knee-pain-relief,shockwave-therapy',
        'body_areas' => 'shoulder,hip,knee,elbow,wrist-hand,ankle-foot,joint', 'featured' => 1,
    ],
    [
        'slug' => 'regenerative-medicine', 'title' => 'Regenerative Medicine', 'category' => 'medical', 'icon' => 'flask',
        'excerpt' => "Non-surgical, biologic-based treatments designed to support the body's natural healing processes in injured or degenerated joints and soft tissues.",
        'hero_text' => "A non-surgical approach that aims to support your body's own healing response in painful joints, tendons and ligaments.",
        'what_is' => "Regenerative medicine refers to treatments that use biologic materials to support the body's natural repair processes. In an orthopedic setting, these therapies are typically directed into a painful joint, tendon or ligament.\n\nAt All Star Health, regenerative options are considered as part of a broader, non-surgical plan that may also include rehabilitation, soft tissue therapy and chiropractic care.",
        'conditions' => "Knee pain and joint wear\nShoulder and rotator cuff irritation\nTendon pain (elbow, Achilles)\nLigament sprains\nHip joint pain\nChronic sports injuries",
        'how_it_works' => "After an evaluation and review of any imaging, your provider determines whether you are a candidate. When appropriate, the treatment is delivered to the target area — often with ultrasound guidance — and paired with a recovery and rehabilitation plan.",
        'benefits' => "Non-surgical treatment option\nDesigned to support natural healing processes\nMay help relieve pain and improve function\nEligibility is determined after evaluation",
        'what_to_expect' => "Your visit begins with a consultation to discuss your goals and history. If treatment is recommended, the procedure is performed in-office. Some soreness is common for a few days. Results vary from person to person, and your provider will explain realistic expectations.",
        'faqs' => [["Am I a candidate for regenerative medicine?", "Candidacy depends on your condition, health history and goals. Your provider will determine eligibility after an evaluation."], ["Is regenerative medicine covered by insurance?", "Coverage varies by plan. Our team can review your benefits and discuss payment options before treatment."]],
        'related' => 'knee-pain-relief,ultrasound-guided-injections-and-diagnostics,shockwave-therapy,trigger-point-and-joint-injections',
        'body_areas' => 'shoulder,hip,knee,elbow,ankle-foot,joint', 'featured' => 1,
    ],
    [
        'slug' => 'shockwave-therapy', 'title' => 'Shockwave Therapy', 'category' => 'medical', 'icon' => 'radio',
        'excerpt' => "Acoustic wave therapy delivered through the skin to stimulate tissue in chronic tendon and soft tissue problems — non-invasive and drug-free.",
        'hero_text' => "Non-invasive acoustic wave therapy for stubborn tendon and soft tissue pain — no needles, no incisions, minimal downtime.",
        'what_is' => "Shockwave therapy (extracorporeal shockwave therapy, or ESWT) delivers focused acoustic pulses through the skin into injured tissue. It is commonly used for chronic tendon and soft tissue conditions that have not responded well to rest alone.\n\nThe treatment is non-invasive and does not require medication, making it a popular option within a non-surgical care plan.",
        'conditions' => "Plantar fasciitis and heel pain\nTennis and golfer's elbow\nShoulder tendinopathy\nAchilles tendon pain\nHip and gluteal tendon pain\nChronic muscle tension",
        'how_it_works' => "Gel is applied to the treatment area and a handheld applicator delivers rapid acoustic pulses. Intensity is adjusted for comfort. Treatments are typically short and are often scheduled as a series.",
        'benefits' => "Non-invasive and drug-free\nMay reduce discomfort in chronic tendon conditions\nDesigned to stimulate the treated tissue\nLittle to no downtime for most patients",
        'what_to_expect' => "Sessions usually last a few minutes per area. You may feel tapping or mild discomfort during treatment and some tenderness afterward. Your provider will recommend the number of sessions based on your evaluation.",
        'faqs' => [["Does shockwave therapy hurt?", "Most patients feel a strong tapping sensation. Intensity is adjusted to keep you as comfortable as possible."], ["How many sessions are typical?", "Plans commonly include a short series of sessions. Your provider will recommend a schedule after evaluating you."]],
        'related' => 'regenerative-medicine,knee-pain-relief,sports-injuries-and-physical-fitness,soft-tissue-management',
        'body_areas' => 'shoulder,hip,knee,elbow,ankle-foot', 'featured' => 1,
    ],
    [
        'slug' => 'pens-dry-needling-treatment', 'title' => 'PENS / Dry Needling Treatment', 'category' => 'medical', 'icon' => 'zap', 'menu_label' => 'PENS / Dry Needling Treatment',
        'excerpt' => "Fine filament needles — with or without gentle electrical stimulation (PENS) — used to target tight, painful muscle and nerve-related pain.",
        'hero_text' => "Targeted needling and percutaneous electrical nerve stimulation to address tight, painful muscles and nerve-related pain.",
        'what_is' => "Dry needling uses thin, sterile filament needles inserted into tight muscle bands and trigger points. Unlike an injection, no medication is delivered — the needle itself is the treatment.\n\nPENS (percutaneous electrical nerve stimulation) adds a mild electrical current through the needles. Both approaches are used within a broader care plan that typically includes movement and soft tissue work.",
        'conditions' => "Muscle knots and trigger points\nNeck and shoulder tension\nLow back pain\nSciatica-type symptoms\nSports-related muscle pain\nChronic myofascial pain",
        'how_it_works' => "Your provider identifies the target muscles, cleans the skin and inserts fine needles. For PENS, small leads are attached and a gentle current is applied for a set time. The needles are then removed.",
        'benefits' => "May help relieve muscle tension and trigger point pain\nDrug-free treatment option\nDesigned to support mobility and rehab participation\nShort in-office sessions",
        'what_to_expect' => "You may feel a brief twitch or deep ache when the needle reaches a tight band. Mild soreness for a day is common. Your provider will discuss how often sessions are recommended.",
        'faqs' => [["Is dry needling the same as acupuncture?", "No. Both use thin needles, but dry needling targets muscles and trigger points based on a musculoskeletal evaluation."], ["What does PENS feel like?", "Most patients describe a light tapping or tingling sensation that is adjusted for comfort."]],
        'related' => 'trigger-point-and-joint-injections,myofascial-release,soft-tissue-management,chiropractic-therapy',
        'body_areas' => 'neck,shoulder,back,leg', 'featured' => 1,
    ],
    [
        'slug' => 'knee-pain-relief', 'title' => 'Knee Pain Relief & Treatment', 'category' => 'medical', 'icon' => 'knee', 'menu_label' => 'Knee Pain Relief & Treatment',
        'excerpt' => "A non-surgical, multidisciplinary approach to knee pain combining evaluation, injections, regenerative options, bracing and rehabilitation.",
        'hero_text' => "Get back to walking, climbing stairs and staying active with a non-surgical knee care plan built around you.",
        'what_is' => "Knee pain can come from joint wear, old injuries, overuse, ligament or meniscus problems, or muscle imbalance. Because the cause differs from person to person, our team starts with a thorough evaluation.\n\nCare may draw on several services under one roof — injections, regenerative medicine, shockwave therapy, bracing, soft tissue therapy and guided exercise — so your plan reflects the cause of your pain rather than a one-size-fits-all program.",
        'conditions' => "Knee joint wear and stiffness\nPain when walking or using stairs\nSports and overuse injuries\nSwelling after activity\nPain behind or around the kneecap\nInstability or weakness",
        'how_it_works' => "We review your history, examine the knee and may use diagnostic ultrasound. Based on findings, your provider recommends a combination of treatments and home exercises, and adjusts the plan as you progress.",
        'benefits' => "May help relieve knee pain and stiffness\nDesigned to support mobility and function\nNon-surgical options under one roof\nPlan built around your goals",
        'what_to_expect' => "Your first visit includes a consultation and examination. Your provider will explain findings, discuss options and outline a plan. Eligibility for specific procedures is determined after evaluation.",
        'faqs' => [["Can knee pain be treated without surgery?", "Many patients explore non-surgical options first. Your provider will discuss which options may be appropriate after an evaluation."], ["Do I need imaging first?", "Not always. Bring any prior imaging you have; your provider will advise whether more is needed."]],
        'related' => 'regenerative-medicine,shockwave-therapy,trigger-point-and-joint-injections,durable-medical-equipment',
        'body_areas' => 'knee,leg,joint', 'featured' => 1,
    ],
    [
        'slug' => 'disc-injury-treatment', 'title' => 'Disc Injury Treatment', 'category' => 'medical', 'icon' => 'spine',
        'excerpt' => "Non-surgical care for bulging and herniated discs, combining decompression, chiropractic care, soft tissue work and medical management.",
        'hero_text' => "Integrated, non-surgical care for neck and back pain related to bulging, herniated or degenerated discs.",
        'what_is' => "Spinal discs act as cushions between the vertebrae. A disc can bulge, herniate or degenerate, sometimes irritating nearby nerves and causing neck or back pain, or symptoms that travel into the arms or legs.\n\nOur integrated team evaluates the source of your symptoms and builds a non-surgical plan that may include spinal decompression, chiropractic care, soft tissue therapy, exercise and medical care.",
        'conditions' => "Bulging or herniated discs\nDegenerative disc changes\nSciatica-type leg pain\nArm pain or tingling from the neck\nLow back pain\nNeck pain",
        'how_it_works' => "After a detailed history, examination and review of any imaging, your provider recommends a combination of therapies designed to reduce pressure and irritation and to restore movement.",
        'benefits' => "May reduce discomfort related to disc problems\nDesigned to support spinal mobility\nNon-surgical, multidisciplinary approach\nEducation on posture and movement",
        'what_to_expect' => "Expect a thorough evaluation on your first visit. Your provider will discuss findings and recommend a plan. Patients with red-flag symptoms will be referred for appropriate additional care.",
        'faqs' => [["Do I need an MRI?", "Not always. If imaging is needed, your provider will explain why and help coordinate it."], ["Can a herniated disc improve without surgery?", "Many patients pursue conservative care first. Your provider will discuss options after evaluating you."]],
        'related' => 'spinal-decompression-therapy,chiropractic-therapy,pens-dry-needling-treatment,soft-tissue-management',
        'body_areas' => 'neck,back',
    ],
    [
        'slug' => 'spinal-decompression-therapy', 'title' => 'Spinal Decompression Therapy', 'category' => 'medical', 'icon' => 'move', 'menu_label' => 'Spinal Decompression Therapy',
        'excerpt' => "Gentle, computer-controlled traction designed to take pressure off spinal discs and nerves in the neck and low back.",
        'hero_text' => "Gentle, controlled traction designed to relieve pressure on spinal discs and nerves — without surgery.",
        'what_is' => "Non-surgical spinal decompression uses a computer-controlled table to apply gentle, cyclical traction to the spine. The goal is to reduce pressure on discs and nearby nerves while you relax.\n\nDecompression is often combined with chiropractic care, soft tissue therapy and exercise as part of a complete plan for neck or low back pain.",
        'conditions' => "Bulging or herniated discs\nDegenerative disc changes\nSciatica-type symptoms\nChronic low back pain\nNeck pain with arm symptoms\nFacet-related pain",
        'how_it_works' => "You lie comfortably on the decompression table, secured with a harness. The system applies and releases traction in controlled cycles tailored to your condition and comfort.",
        'benefits' => "May help relieve disc-related back and neck pain\nDesigned to reduce pressure on spinal structures\nNon-invasive and drug-free\nRelaxing, comfortable sessions",
        'what_to_expect' => "Sessions typically last around 20–30 minutes and are scheduled as a series. Most patients find decompression relaxing. Your provider will determine eligibility after evaluation.",
        'faqs' => [["Is spinal decompression painful?", "Most patients find it comfortable and relaxing. Settings are adjusted to your tolerance."], ["Who should not have decompression?", "Certain conditions may make decompression inappropriate. Your provider will screen for these during your evaluation."]],
        'related' => 'disc-injury-treatment,chiropractic-therapy,soft-tissue-management,active-passive-stretching',
        'body_areas' => 'neck,back', 'featured' => 1,
    ],
    [
        'slug' => 'durable-medical-equipment', 'title' => 'Durable Medical Equipment', 'category' => 'medical', 'icon' => 'accessibility',
        'excerpt' => "Braces, supports and other medical equipment recommended by your provider to support stability, protection and recovery.",
        'hero_text' => "Supportive braces and equipment selected by your provider to protect injured areas and support recovery at home.",
        'what_is' => "Durable medical equipment (DME) includes items such as braces, supports and home-use devices prescribed or recommended as part of your treatment. The right equipment can support stability and protect an injured area while you heal.\n\nOur team helps determine which equipment fits your condition, fits you properly and works with your care plan.",
        'conditions' => "Knee instability or pain\nBack and lumbar support needs\nNeck injuries\nWrist and hand strain\nAnkle sprains\nPost-injury protection",
        'how_it_works' => "Your provider recommends equipment based on your evaluation. Our staff will help with sizing, fitting and instructions for use, and can review insurance coverage where applicable.",
        'benefits' => "Designed to support stability and protection\nMay reduce discomfort during daily activity\nFitted for your body and condition\nComplements in-office treatment",
        'what_to_expect' => "If equipment is recommended, we'll explain why, show you how to use it and discuss coverage. Follow your provider's guidance on how long to wear or use it.",
        'faqs' => [["Is equipment covered by insurance?", "Coverage depends on your plan. Our team can verify benefits before you receive equipment."]],
        'related' => 'knee-pain-relief,work-injury-compensation,car-accident-injury-treatment,sports-injuries-and-physical-fitness',
        'body_areas' => 'back,knee,wrist-hand,ankle-foot',
    ],
    [
        'slug' => 'pit-treatment', 'title' => 'PIT Treatment', 'category' => 'medical', 'icon' => 'activity',
        'excerpt' => "An in-office treatment offered by our medical team as part of an integrated, non-surgical pain care plan.",
        'hero_text' => "An in-office treatment option offered by our medical providers as part of your personalized care plan.",
        'what_is' => "PIT treatment is one of the in-office services provided by the All Star Health medical team. Your provider will explain how the treatment works, whether it is appropriate for your condition and how it fits alongside other therapies in your plan.",
        'conditions' => "",
        'how_it_works' => "Treatment begins with a consultation and evaluation. If PIT treatment is recommended, your provider will walk you through the process before you begin.",
        'benefits' => "Delivered by our medical team\nPart of an integrated, non-surgical plan\nEligibility is determined after evaluation",
        'what_to_expect' => "Call our team or request an appointment to learn more about PIT treatment and whether it may be right for you.",
        'faqs' => [],
        'related' => 'trigger-point-and-joint-injections,regenerative-medicine,shockwave-therapy',
        'body_areas' => '',
    ],
    [
        'slug' => 'iv-therapy', 'title' => 'IV Therapy', 'category' => 'medical', 'icon' => 'droplet', 'menu_label' => 'IV Therapy — Coming Soon', 'coming_soon' => 1,
        'excerpt' => "IV therapy is coming soon to All Star Health. Contact our team to be notified when it becomes available.",
        'hero_text' => "Coming soon to All Star Health. Contact our team to learn more and be notified when IV therapy is available.",
        'what_is' => "We are preparing to offer IV therapy at All Star Health. Details about available options will be posted here once the service launches.",
        'conditions' => "", 'how_it_works' => "", 'benefits' => "", 'what_to_expect' => "Call 844-844-4755 to ask about IV therapy availability.",
        'faqs' => [], 'related' => 'regenerative-medicine,theramine', 'body_areas' => '',
    ],

    // ---------------- Soft Tissue ----------------
    [
        'slug' => 'soft-tissue-management', 'title' => 'Soft Tissue Management', 'category' => 'soft-tissue', 'icon' => 'waves',
        'excerpt' => "Hands-on and instrument-assisted therapies for muscles, fascia and connective tissue — designed to ease tension and support movement.",
        'hero_text' => "Hands-on and instrument-assisted therapies that address the muscles and fascia behind pain and restricted movement.",
        'what_is' => "Muscles, tendons and fascia often play a major role in pain and stiffness. Soft tissue management is our umbrella of hands-on and tool-assisted techniques used to address these tissues.\n\nDepending on your needs, your plan may include active and passive stretching, myofascial release, Gua Sha, cupping or Theragun therapy — usually alongside chiropractic or medical care.",
        'conditions' => "Muscle tightness and knots\nNeck and back tension\nSports-related soreness\nRestricted range of motion\nScar tissue and adhesions\nPostural strain",
        'how_it_works' => "Your clinician assesses the involved muscles and fascia, then selects the techniques best suited to your condition, comfort level and goals.",
        'benefits' => "May reduce muscle tension and discomfort\nDesigned to support flexibility and mobility\nComplements chiropractic and medical care\nTailored to your body",
        'what_to_expect' => "Sessions are hands-on and adjusted to your comfort. Some soreness, similar to after a workout, is normal. You may also receive stretches to do at home.",
        'faqs' => [["Which soft tissue technique is right for me?", "Your clinician will choose techniques based on your evaluation, goals and comfort."]],
        'related' => 'myofascial-release,active-passive-stretching,cupping-therapy,theragun-therapy',
        'body_areas' => 'neck,shoulder,back,leg',
    ],
    [
        'slug' => 'active-passive-stretching', 'title' => 'Active & Passive Stretching', 'category' => 'soft-tissue', 'icon' => 'move',
        'excerpt' => "Clinician-guided stretching to improve flexibility, ease muscle tension and support healthy joint motion.",
        'hero_text' => "Guided stretching that helps restore flexibility and range of motion as part of your recovery.",
        'what_is' => "Passive stretching is performed with the help of a clinician while you relax. Active stretching involves you engaging muscles to move into the stretch. Combining both may help improve flexibility and support healthier movement patterns.",
        'conditions' => "Tight hamstrings and hips\nNeck and shoulder stiffness\nLow back tightness\nPostural strain\nPost-injury stiffness\nAthletic recovery",
        'how_it_works' => "Your clinician guides you through targeted stretches, adjusting position and intensity. You will also learn stretches to continue at home.",
        'benefits' => "Designed to support flexibility and range of motion\nMay reduce muscle tension\nTeaches safe home stretching\nComplements other therapies",
        'what_to_expect' => "Wear comfortable clothing. Stretching should feel like a strong but tolerable pull — tell your clinician if anything is painful.",
        'faqs' => [],
        'related' => 'soft-tissue-management,myofascial-release,chiropractic-therapy,sports-injuries-and-physical-fitness',
        'body_areas' => 'hip,back,leg',
    ],
    [
        'slug' => 'myofascial-release', 'title' => 'Myofascial Release', 'category' => 'soft-tissue', 'icon' => 'hand',
        'excerpt' => "Sustained, hands-on pressure applied to restricted fascia and muscle to help ease tension and improve movement.",
        'hero_text' => "Hands-on therapy for restricted fascia and tight muscles that contribute to pain and limited movement.",
        'what_is' => "Fascia is the connective tissue that surrounds and supports muscles. When it becomes tight or restricted, it can contribute to pain and limited motion. Myofascial release uses sustained, gentle-to-firm pressure to address these restrictions.",
        'conditions' => "Neck and shoulder tension\nLow back pain\nTrigger points\nPostural strain\nSports-related tightness\nRestricted range of motion",
        'how_it_works' => "Your clinician locates areas of restriction and applies steady pressure and stretch until the tissue releases, adjusting to your comfort.",
        'benefits' => "May help ease muscle and fascial tension\nDesigned to support range of motion\nNon-invasive and drug-free\nPairs well with stretching and adjustments",
        'what_to_expect' => "You may feel deep pressure or a stretching sensation. Mild soreness afterward is normal and typically short-lived.",
        'faqs' => [],
        'related' => 'soft-tissue-management,gua-sha-technique,cupping-therapy,pens-dry-needling-treatment',
        'body_areas' => 'neck,shoulder,back,leg',
    ],
    [
        'slug' => 'gua-sha-technique', 'title' => 'Gua Sha Technique', 'category' => 'soft-tissue', 'icon' => 'sparkles', 'menu_label' => 'Gua Sha Technique',
        'excerpt' => "An instrument-assisted soft tissue technique using a smooth-edged tool to address tight muscles and fascia.",
        'hero_text' => "Instrument-assisted soft tissue work that targets tight muscles and fascia.",
        'what_is' => "Gua Sha is an instrument-assisted technique in which a smooth-edged tool is stroked across the skin over tight or restricted tissue. It is used to address muscle tension and fascial restriction as part of a soft tissue plan.",
        'conditions' => "Muscle tightness\nNeck and upper back tension\nTendon irritation\nSports-related soreness\nRestricted movement",
        'how_it_works' => "After applying a lubricant, your clinician uses the tool with controlled strokes over the treatment area, adjusting pressure for comfort.",
        'benefits' => "May help reduce muscle tension\nDesigned to support tissue mobility\nQuick, targeted sessions\nComplements stretching and exercise",
        'what_to_expect' => "Temporary redness or light marks on the skin are common and usually fade within a few days.",
        'faqs' => [],
        'related' => 'myofascial-release,cupping-therapy,soft-tissue-management,theragun-therapy',
        'body_areas' => 'neck,shoulder,back,elbow',
    ],
    [
        'slug' => 'cupping-therapy', 'title' => 'Cupping Therapy', 'category' => 'soft-tissue', 'icon' => 'circle-dot',
        'excerpt' => "Suction cups placed on the skin to lift and decompress soft tissue — used to ease muscle tension and support movement.",
        'hero_text' => "A soft tissue technique that uses gentle suction to lift and decompress tight muscles and fascia.",
        'what_is' => "Cupping therapy uses cups that create suction on the skin, gently lifting the underlying tissue. In a musculoskeletal setting, it is used to address muscle tension and fascial restriction.",
        'conditions' => "Back and shoulder tension\nMuscle knots\nSports recovery\nNeck stiffness\nFascial restriction",
        'how_it_works' => "Cups are placed on the treatment area and may remain stationary or be glided along the muscle while you move or relax.",
        'benefits' => "May help ease muscle tension\nDesigned to support tissue mobility\nNon-invasive and drug-free\nPairs well with other soft tissue care",
        'what_to_expect' => "Circular marks are common after cupping and typically fade over several days.",
        'faqs' => [],
        'related' => 'myofascial-release,gua-sha-technique,soft-tissue-management,theragun-therapy',
        'body_areas' => 'shoulder,back,leg',
    ],
    [
        'slug' => 'theragun-therapy', 'title' => 'Theragun Therapy', 'category' => 'soft-tissue', 'icon' => 'activity',
        'excerpt' => "Percussive therapy that delivers rapid pulses into muscle tissue to help ease tension and support recovery.",
        'hero_text' => "Percussive muscle therapy that helps ease tension and supports recovery between treatments.",
        'what_is' => "Theragun therapy uses a handheld percussive device to deliver rapid, targeted pulses into muscle tissue. It is commonly used to address muscle tension and support recovery as part of a soft tissue plan.",
        'conditions' => "Muscle tension and soreness\nSports recovery\nTight hips and legs\nBack and shoulder tension",
        'how_it_works' => "Your clinician moves the device over targeted muscle groups, adjusting speed and attachment for comfort and depth.",
        'benefits' => "May help ease muscle tension\nDesigned to support recovery\nQuick and comfortable\nComplements stretching",
        'what_to_expect' => "Most patients find percussive therapy comfortable. Let your clinician know if you'd like more or less pressure.",
        'faqs' => [],
        'related' => 'soft-tissue-management,active-passive-stretching,cupping-therapy,sports-injuries-and-physical-fitness',
        'body_areas' => 'back,leg,shoulder',
    ],

    // ---------------- Injury & Accident Care ----------------
    [
        'slug' => 'car-accident-injury-treatment', 'title' => 'Car Accident Injury Treatment', 'category' => 'injury', 'icon' => 'car', 'menu_label' => 'Car Accident Injury Treatment',
        'excerpt' => "Evaluation and treatment after an automobile injury — including whiplash, neck and back pain — from an integrated medical and chiropractic team.",
        'hero_text' => "Hurt in a car accident? Get evaluated and start a coordinated recovery plan with our medical and chiropractic team.",
        'what_is' => "Car accidents can cause injuries such as whiplash, muscle strains, joint sprains and disc problems. Symptoms are sometimes delayed by hours or days, which is why a prompt evaluation matters.\n\nAll Star Health provides dedicated automobile injury care. Our integrated team can evaluate your injuries, document findings and provide treatment that may include chiropractic care, soft tissue therapy, rehabilitation and medical care.",
        'conditions' => "Whiplash and neck pain\nBack pain\nHeadaches after an accident\nShoulder and joint injuries\nMuscle strains and sprains\nDisc-related symptoms",
        'how_it_works' => "We begin with a thorough history and examination, then build a treatment plan around your injuries. Our team can help with the paperwork involved in accident care.",
        'benefits' => "Prompt evaluation after an accident\nCoordinated medical and chiropractic care\nDesigned to support recovery and function\nHelp with accident-related documentation",
        'what_to_expect' => "Bring your claim information and any records from urgent care or the ER. Same-day appointments are offered when availability permits. Download and complete our Accident Forms before your visit to save time.",
        'faqs' => [["Do you treat car accident injuries?", "Yes. Dedicated automobile injury treatment is available at both our Gilbert and Tempe offices."], ["What should I bring to my first visit?", "Bring your ID, insurance or claim information, and any medical records from the accident. Completing the Accident Forms in advance helps."]],
        'related' => 'chiropractic-therapy,disc-injury-treatment,soft-tissue-management,work-injury-compensation',
        'body_areas' => 'neck,back,shoulder',
        'featured' => 1,
    ],
    [
        'slug' => 'work-injury-compensation', 'title' => 'Work Injury / Workers Compensation', 'category' => 'injury', 'icon' => 'briefcase', 'menu_label' => 'Work Injury / Workers Compensation',
        'excerpt' => "Evaluation and care for work-related injuries, with an integrated team focused on helping you return to work and daily life.",
        'hero_text' => "Evaluation and care for work-related injuries — focused on recovery, function and getting you back to your routine.",
        'what_is' => "Work injuries range from lifting strains and repetitive stress to slips and falls. All Star Health provides evaluation and care for work-related injuries, coordinating chiropractic, soft tissue, rehabilitation and medical services as needed.",
        'conditions' => "Lifting injuries and back strain\nRepetitive stress injuries\nNeck and shoulder pain\nSlip and fall injuries\nWrist and hand strain\nKnee injuries",
        'how_it_works' => "Your visit starts with a history and examination focused on how the injury happened and how it affects your work. Your plan is designed around restoring function.",
        'benefits' => "Evaluation and care for work-related injuries\nCoordinated, multidisciplinary approach\nDesigned to support return to activity\nHelp with documentation",
        'what_to_expect' => "Bring your claim number and employer or carrier information if available. Our team can help verify coverage before your visit.",
        'faqs' => [["Do you treat work injuries?", "Yes. Work injury treatment is available. Call us to discuss your claim and schedule an evaluation."]],
        'related' => 'car-accident-injury-treatment,chiropractic-therapy,durable-medical-equipment,soft-tissue-management',
        'body_areas' => 'back,shoulder,wrist-hand,knee',
    ],
    [
        'slug' => 'sports-injuries-and-physical-fitness', 'title' => 'Sports Injuries & Physical Fitness', 'category' => 'injury', 'icon' => 'dumbbell', 'menu_label' => 'Sports Injuries & Physical Fitness',
        'excerpt' => "Care for athletes and active people — from sprains and strains to overuse injuries — focused on recovery, function and return to activity.",
        'hero_text' => "Care for athletes and active people, focused on recovery, performance and getting back to what you love.",
        'what_is' => "Whether you're a weekend warrior, a student athlete or simply active, injuries can interrupt your routine. Our team evaluates sports injuries and builds plans that may combine chiropractic care, soft tissue therapy, shockwave, regenerative options and guided exercise.",
        'conditions' => "Sprains and strains\nTendon overuse injuries\nShoulder and elbow pain\nKnee and ankle injuries\nMuscle tightness and imbalance\nReturn-to-sport conditioning",
        'how_it_works' => "We look at how you move and the demands of your sport, identify contributing factors and create a progressive plan to help you return to activity.",
        'benefits' => "Designed to support recovery and function\nMay reduce discomfort from overuse injuries\nGuidance on safe return to activity\nMultiple therapies under one roof",
        'what_to_expect' => "Wear athletic clothing to your visit. Your clinician may assess movement patterns and provide exercises to continue at home or in the gym.",
        'faqs' => [],
        'related' => 'shockwave-therapy,regenerative-medicine,soft-tissue-management,chiropractic-therapy',
        'body_areas' => 'shoulder,elbow,knee,leg,ankle-foot',
        'featured' => 1,
    ],

    // ---------------- Chiropractic ----------------
    [
        'slug' => 'chiropractic-therapy', 'title' => 'Chiropractic Therapy', 'category' => 'chiropractic', 'icon' => 'spine',
        'excerpt' => "Spinal and joint adjustments from experienced chiropractors, combined with soft tissue care and rehab, to support alignment, motion and function.",
        'hero_text' => "Experienced chiropractors working alongside our medical team to support alignment, mobility and everyday function.",
        'what_is' => "Chiropractic care focuses on the spine, joints and nervous system. Our chiropractors use adjustments and mobilization to address restricted joints, often combined with soft tissue therapy, stretching and exercise.\n\nAt All Star Health, chiropractors work alongside medical providers and rehabilitation professionals, so your care can draw on more than one discipline when needed.",
        'conditions' => "Neck pain and stiffness\nLow back pain\nHeadaches related to neck tension\nPostural strain\nAuto and work injuries\nJoint restriction",
        'how_it_works' => "After a history and examination, your chiropractor explains the findings and recommends a plan. Adjustments are tailored to your comfort, age and condition, and may be paired with soft tissue care and home exercises.",
        'benefits' => "May help relieve neck and back discomfort\nDesigned to support mobility and joint function\nWorks alongside medical and rehab care\nPersonalized, not a generic long-term program",
        'what_to_expect' => "Your first visit includes a consultation and examination. Many patients receive treatment the same day. Your chiropractor will explain each step and answer questions.",
        'faqs' => [["Is chiropractic care safe?", "Your chiropractor will screen your history and tailor treatment to you. Gentle techniques are available."], ["Do I need a referral?", "A referral is generally not required. Our team can verify your insurance benefits before your visit."]],
        'related' => 'spinal-decompression-therapy,soft-tissue-management,disc-injury-treatment,car-accident-injury-treatment',
        'body_areas' => 'neck,back,shoulder,hip,joint',
        'featured' => 1,
    ],

    // ---------------- Allergy ----------------
    [
        'slug' => 'allergy-drops-for-environmental-allergies', 'title' => 'Allergy Drops — Environmental Allergies', 'category' => 'allergy', 'icon' => 'droplet', 'menu_label' => 'Allergy Drops — Environmental Allergies',
        'excerpt' => "Sublingual (under-the-tongue) allergy drops — a needle-free form of immunotherapy for environmental allergies, taken at home.",
        'hero_text' => "Needle-free immunotherapy for environmental allergies that you take at home, under your provider's guidance.",
        'what_is' => "Allergy drops (sublingual immunotherapy) contain small amounts of the allergens you react to, placed under the tongue. Over time, immunotherapy is designed to help the immune system become less reactive to those allergens.\n\nTreatment begins with allergy testing so your drops are based on your specific triggers.",
        'conditions' => "Seasonal pollen allergies\nDust mite allergies\nPet dander allergies\nMold allergies\nAllergic nasal congestion",
        'how_it_works' => "After testing identifies your triggers, your provider prescribes a custom formula. You take the drops at home daily and attend periodic follow-ups.",
        'benefits' => "Needle-free immunotherapy option\nTaken conveniently at home\nBased on your allergy testing\nMay reduce allergy symptoms over time",
        'what_to_expect' => "Your provider will review your test results, explain how to take the drops and schedule follow-ups to monitor progress.",
        'faqs' => [["How long does allergy immunotherapy take?", "Immunotherapy is a longer-term treatment. Your provider will discuss expected duration based on your plan."]],
        'related' => 'allergy-testing,allergy-shots-for-environmental-allergies,environmental-allergies,nasal-congestion',
        'body_areas' => '',
    ],
    [
        'slug' => 'allergy-shots-for-environmental-allergies', 'title' => 'Allergy Shots — Environmental Allergies', 'category' => 'allergy', 'icon' => 'syringe', 'menu_label' => 'Allergy Shots — Environmental Allergies',
        'excerpt' => "Subcutaneous immunotherapy (allergy shots) for environmental allergies, administered in-office on a schedule set by your provider.",
        'hero_text' => "In-office immunotherapy for environmental allergies, tailored to the triggers identified through testing.",
        'what_is' => "Allergy shots (subcutaneous immunotherapy) deliver gradually increasing doses of the allergens you are sensitive to. Over time, this is designed to help reduce your immune system's reaction.\n\nTreatment is based on allergy testing and administered in-office, where you are monitored after each injection.",
        'conditions' => "Seasonal pollen allergies\nDust mite allergies\nPet dander allergies\nMold allergies\nAllergic rhinitis",
        'how_it_works' => "Shots begin with a build-up phase, during which doses increase gradually, followed by a maintenance phase. Your provider sets the schedule.",
        'benefits' => "Based on your specific triggers\nAdministered and monitored in-office\nMay reduce allergy symptoms over time\nStructured treatment schedule",
        'what_to_expect' => "Plan to stay in the office for a short observation period after each shot. Your provider will discuss the schedule and duration with you.",
        'faqs' => [],
        'related' => 'allergy-testing,allergy-drops-for-environmental-allergies,environmental-allergies,chronic-sinus-infections',
        'body_areas' => '',
    ],
    [
        'slug' => 'food-allergies', 'title' => 'Food Allergies', 'category' => 'allergy', 'icon' => 'leaf',
        'excerpt' => "Evaluation and management of food allergies and sensitivities, starting with a careful history and appropriate testing.",
        'hero_text' => "Evaluation and management of food allergies, starting with a careful history and appropriate testing.",
        'what_is' => "Food allergies occur when the immune system reacts to certain foods. Reactions can range from mild symptoms to serious ones. Our providers evaluate your history and symptoms and may recommend testing to help identify triggers.",
        'conditions' => "Reactions after eating certain foods\nHives related to foods\nDigestive symptoms after meals\nSuspected food sensitivities",
        'how_it_works' => "Your provider reviews your symptoms and history, recommends appropriate testing and builds a management plan, including guidance on avoiding triggers.",
        'benefits' => "Helps identify likely triggers\nPersonalized management plan\nEducation on avoiding reactions\nCoordinated with your other care",
        'what_to_expect' => "Bring notes on foods you suspect and the reactions you've had. If you have ever had a severe reaction, tell our team when scheduling. In an emergency, call 911.",
        'faqs' => [],
        'related' => 'allergy-testing,hives-urticaria,environmental-allergies',
        'body_areas' => '',
    ],
    [
        'slug' => 'allergy-testing', 'title' => 'Allergy Testing', 'category' => 'allergy', 'icon' => 'clipboard',
        'excerpt' => "In-office allergy testing to help identify the environmental and other triggers behind your symptoms.",
        'hero_text' => "Find out what's behind your symptoms with in-office allergy testing.",
        'what_is' => "Allergy testing helps identify the specific substances that trigger your symptoms — such as pollens, dust mites, pet dander or molds. Results guide treatment options including avoidance strategies, medications and immunotherapy.",
        'conditions' => "Seasonal allergy symptoms\nYear-round congestion or sneezing\nItchy, watery eyes\nHives\nSuspected food allergies\nRecurring sinus problems",
        'how_it_works' => "Your provider reviews your history and selects an appropriate panel. Testing is performed in-office and results are reviewed with you.",
        'benefits' => "Identifies your specific triggers\nGuides a personalized treatment plan\nPerformed in-office\nFoundation for immunotherapy",
        'what_to_expect' => "Some medications, such as antihistamines, can affect results. Our team will tell you what to pause before testing.",
        'faqs' => [["Do I need to stop medications before testing?", "Some medications can interfere with results. Our team will give you specific instructions when you schedule."]],
        'related' => 'allergy-drops-for-environmental-allergies,allergy-shots-for-environmental-allergies,food-allergies,environmental-allergies',
        'body_areas' => '',
    ],
    [
        'slug' => 'hives-urticaria', 'title' => 'Hives / Urticaria', 'category' => 'allergy', 'icon' => 'circle-dot', 'menu_label' => 'Hives / Urticaria',
        'excerpt' => "Evaluation and management of hives — itchy, raised welts on the skin — including identifying possible triggers.",
        'hero_text' => "Evaluation and management of hives, with a focus on identifying possible triggers.",
        'what_is' => "Hives (urticaria) are itchy, raised welts that can appear suddenly. They may be triggered by allergens, foods, medications, infections or other factors, and sometimes no clear cause is found. Our providers evaluate your history and help develop a management plan.",
        'conditions' => "Acute hives\nRecurring or chronic hives\nHives after foods or medications\nItchy skin welts",
        'how_it_works' => "Your provider reviews your symptoms and history, may recommend testing and discusses treatment and trigger-avoidance options.",
        'benefits' => "Helps identify possible triggers\nPersonalized management plan\nCoordinated with allergy testing\nOngoing follow-up",
        'what_to_expect' => "Photos of past flare-ups can be helpful. If you experience swelling of the lips, tongue or throat, or trouble breathing, call 911.",
        'faqs' => [],
        'related' => 'allergy-testing,food-allergies,environmental-allergies',
        'body_areas' => '',
    ],
    [
        'slug' => 'nasal-congestion', 'title' => 'Nasal Congestion', 'category' => 'allergy', 'icon' => 'wind',
        'excerpt' => "Evaluation and care for ongoing nasal congestion, including allergy-related causes.",
        'hero_text' => "Breathe easier. Evaluation and care for persistent nasal congestion, including allergy-related causes.",
        'what_is' => "Persistent nasal congestion can be caused by allergies, irritants, sinus problems and other factors. Our providers evaluate your symptoms and may recommend allergy testing to help identify the cause.",
        'conditions' => "Year-round stuffy nose\nSeasonal congestion\nPost-nasal drip\nAllergic rhinitis",
        'how_it_works' => "After an evaluation, your provider recommends a plan that may include testing, medications and immunotherapy when allergies are involved.",
        'benefits' => "Looks for the cause of congestion\nPersonalized treatment options\nAllergy testing available in-office\nOngoing follow-up",
        'what_to_expect' => "Let us know which medications you've already tried and how long symptoms have lasted.",
        'faqs' => [],
        'related' => 'chronic-sinus-infections,allergy-testing,environmental-allergies,allergy-drops-for-environmental-allergies',
        'body_areas' => '',
    ],
    [
        'slug' => 'chronic-sinus-infections', 'title' => 'Chronic Sinus Infections', 'category' => 'allergy', 'icon' => 'wind',
        'excerpt' => "Evaluation and care for recurring sinus problems, including identifying allergy-related contributors.",
        'hero_text' => "Evaluation and care for recurring sinus problems, including allergy-related contributors.",
        'what_is' => "Recurring or long-lasting sinus problems can significantly affect quality of life. Allergies are one possible contributor. Our providers evaluate your history and symptoms and may recommend allergy testing as part of your plan.",
        'conditions' => "Recurring sinus infections\nFacial pressure and congestion\nPost-nasal drip\nAllergy-related sinus symptoms",
        'how_it_works' => "Your provider reviews your history, examines you and recommends a plan that may include testing and treatment of underlying allergies.",
        'benefits' => "Looks for underlying contributors\nPersonalized treatment plan\nCoordinated allergy care\nOngoing follow-up",
        'what_to_expect' => "Bring a list of past treatments and how often infections occur. Your provider will discuss options and referrals if needed.",
        'faqs' => [],
        'related' => 'nasal-congestion,allergy-testing,allergy-shots-for-environmental-allergies,environmental-allergies',
        'body_areas' => '',
    ],
    [
        'slug' => 'environmental-allergies', 'title' => 'Environmental Allergies', 'category' => 'allergy', 'icon' => 'flower',
        'excerpt' => "Testing and treatment for allergies to pollen, dust mites, pet dander, molds and other environmental triggers.",
        'hero_text' => "Testing and treatment options for pollen, dust, pet and mold allergies.",
        'what_is' => "Environmental allergies are reactions to substances such as pollens, dust mites, pet dander and molds. Symptoms may include sneezing, congestion, itchy eyes and more. Our providers offer testing and treatment options including allergy drops and allergy shots.",
        'conditions' => "Seasonal allergies\nDust mite allergies\nPet allergies\nMold allergies\nItchy, watery eyes\nSneezing and congestion",
        'how_it_works' => "Testing identifies your triggers. Your provider then recommends a plan that may include avoidance strategies, medications and immunotherapy.",
        'benefits' => "Identifies specific triggers\nNeedle-free and in-office immunotherapy options\nPersonalized plan\nOngoing follow-up",
        'what_to_expect' => "Your provider will explain testing preparation, review results with you and discuss treatment options.",
        'faqs' => [],
        'related' => 'allergy-testing,allergy-drops-for-environmental-allergies,allergy-shots-for-environmental-allergies,nasal-congestion',
        'body_areas' => '',
    ],

    // ---------------- Medical Foods ----------------
    [
        'slug' => 'theramine', 'title' => 'Theramine', 'category' => 'medical-foods', 'icon' => 'pill',
        'excerpt' => "A prescription medical food that may be recommended by your provider as part of a plan for managing pain.",
        'hero_text' => "A prescription medical food your provider may recommend as part of a pain management plan.",
        'what_is' => "Theramine is a prescription medical food formulated for the dietary management of pain syndromes. Medical foods are used under physician supervision to address specific nutritional needs associated with a condition.\n\nYour provider will determine whether Theramine is appropriate as part of your overall care plan.",
        'conditions' => "Chronic pain conditions\nMusculoskeletal pain\nPain management plans",
        'how_it_works' => "If recommended, your provider will explain dosing and how Theramine fits with your other treatments and medications.",
        'benefits' => "Used under physician supervision\nPart of an integrated pain management plan\nEligibility is determined after evaluation",
        'what_to_expect' => "Tell your provider about all medications and supplements you take so they can determine whether Theramine is appropriate.",
        'faqs' => [["What is a medical food?", "A medical food is formulated to be used under physician supervision for the dietary management of a specific condition."]],
        'related' => 'percura,trepadone,trigger-point-and-joint-injections',
        'body_areas' => 'joint',
    ],
    [
        'slug' => 'percura', 'title' => 'Percura', 'category' => 'medical-foods', 'icon' => 'pill',
        'excerpt' => "A prescription medical food that may be recommended by your provider as part of a care plan for nerve-related discomfort.",
        'hero_text' => "A prescription medical food your provider may recommend as part of a care plan for nerve-related symptoms.",
        'what_is' => "Percura is a prescription medical food formulated for the dietary management of the metabolic processes associated with peripheral neuropathy-related symptoms. It is used under physician supervision.\n\nYour provider will determine whether Percura is appropriate for you.",
        'conditions' => "Nerve-related discomfort\nNumbness or tingling\nPeripheral neuropathy symptoms",
        'how_it_works' => "If recommended, your provider will explain dosing and how Percura fits with your other treatments and medications.",
        'benefits' => "Used under physician supervision\nPart of an integrated care plan\nEligibility is determined after evaluation",
        'what_to_expect' => "Tell your provider about all medications and supplements you take so they can determine whether Percura is appropriate.",
        'faqs' => [],
        'related' => 'theramine,trepadone,pens-dry-needling-treatment',
        'body_areas' => '',
    ],
    [
        'slug' => 'trepadone', 'title' => 'Trepadone', 'category' => 'medical-foods', 'icon' => 'pill',
        'excerpt' => "A prescription medical food that may be recommended by your provider as part of a care plan for joint-related discomfort.",
        'hero_text' => "A prescription medical food your provider may recommend as part of a care plan for joint discomfort.",
        'what_is' => "Trepadone is a prescription medical food formulated for the dietary management of joint disorders and associated inflammation. It is used under physician supervision.\n\nYour provider will determine whether Trepadone is appropriate as part of your plan.",
        'conditions' => "Joint discomfort\nJoint stiffness\nOsteoarthritis-related symptoms",
        'how_it_works' => "If recommended, your provider will explain dosing and how Trepadone fits with your other treatments and medications.",
        'benefits' => "Used under physician supervision\nPart of an integrated joint care plan\nEligibility is determined after evaluation",
        'what_to_expect' => "Tell your provider about all medications and supplements you take so they can determine whether Trepadone is appropriate.",
        'faqs' => [],
        'related' => 'theramine,percura,knee-pain-relief',
        'body_areas' => 'joint,knee',
    ],

    // ---------------- Extra pages to audit (kept as drafts) ----------------
    [
        'slug' => 'whartons-jelly', 'title' => "Wharton's Jelly", 'category' => 'medical', 'icon' => 'flask', 'status' => 'draft', 'show_in_menu' => 0,
        'excerpt' => "A regenerative medicine option discussed with patients following evaluation. (Draft — confirm with the client before publishing.)",
        'hero_text' => "A regenerative medicine option discussed with patients after evaluation.",
        'what_is' => "This page existed on the previous website. Confirm whether the service is still offered, then paste the approved copy here and publish.",
        'conditions' => '', 'how_it_works' => '', 'benefits' => '', 'what_to_expect' => '', 'faqs' => [],
        'related' => 'regenerative-medicine', 'body_areas' => '',
    ],
    [
        'slug' => 'prolotherapy', 'title' => 'Prolotherapy', 'category' => 'medical', 'icon' => 'syringe', 'status' => 'draft', 'show_in_menu' => 0,
        'excerpt' => "An injection-based treatment discussed with patients following evaluation. (Draft — confirm with the client before publishing.)",
        'hero_text' => "An injection-based treatment option discussed with patients after evaluation.",
        'what_is' => "This page existed on the previous website. Confirm whether the service is still offered, then paste the approved copy here and publish.",
        'conditions' => '', 'how_it_works' => '', 'benefits' => '', 'what_to_expect' => '', 'faqs' => [],
        'related' => 'regenerative-medicine,trigger-point-and-joint-injections', 'body_areas' => '',
    ],
];
